language: node_js

node_js:
  - '8'


scirpt:
  - "npm test"
  - "npm run build"

after_success:
  - "echo 'success!'"
  - "openssl aes-256-cbc -K $encrypted_8672fb34074e_key -iv $encrypted_8672fb34074e_iv -in .travis_rsa.enc -out ./.travis_rsa -d"
  - "mv ./.travis_rsa $HOME/.ssh/id_rsa"
  - "cd dist"
  - 'git config --global user.name "kamataryo@travis"'
  - 'git config --global user.mail "kamataryo@no-reply.github.io"'
  - "git init"
  - "git remote add origin git@github.com:kamataryo/wbk201708-travis-gh-pages-deploy-demo.git"
  - "git checkout -b gh-pages"
  - "git add ."
  - "git commit -m\"Deploy from travis[ci skip]\""
  - "git push origin gh-pages"
